### PR TITLE
Update google_java_format.lua

### PR DESCRIPTION
**Pull request by kuator**

### CODE REVIEW

**Comment by creativenull** [comment]
Any status on this? It has been in draft mode for some time now 😅

**Comment by kimabrandt** [comment]
Maybe something like the [black](https://github.com/creativenull/efmls-configs-nvim/blob/ddc7c542aaad21da594edba233c15ae3fad01ea0/lua/efmls-configs/formatters/black.lua) one!?

```lua
local google_java = {
    prefix = "google-java-format",
    formatCommand = fs.executable("google-java-format")
        .. " --aosp" -- Use AOSP style instead of Google Style (4-space indentation).
        .. " $(echo -n ${--useless:rowStart} ${--useless:rowEnd}"
        .. " | xargs -n4 -r sh -c 'echo"
        .. " --skip-sorting-imports" -- Do not fix the import order.
        .. " --skip-removing-unused-imports" -- Do not remove unused imports.
        .. " --skip-reflowing-long-strings" -- Do not reflow string literals that exceed the column limit.
        .. " --skip-javadoc-formatting" -- Do not reformat javadoc.
        .. " --lines $(($1+1)):$(($3+1))'" -- Line range(s) to format, like 5:10 (1-based; default is all).
        .. ") -",
    formatCanRange = true,
    formatStdin = true,
    rootMarkers = {
        ".project",
        "classpath",
        "pom.xml",
    },
}
```
I prefer 4 spaces :smile:

**Comment by kuator** [comment]
> Any status on this? It has been in draft mode for some time now 😅
Sorry, life happened so I've been busy with other stuff. If you want me to, I can close it

**Comment by creativenull** [comment]
No worries take care, you're always welcome to come back to it if you want :)

**Comment by creativenull** [comment]
@kimabrandt it doesn't look cross-platform, so this won't work on Windows for example.

**Comment by kuator** [comment]
> @kimabrandt it doesn't look cross-platform, so this won't work on Windows for example.

Until efm implements separation of range-formatting parameters, I think we can keep the old command in windows just like we did in black.

**Comment by kuator** [comment]
> Maybe something like the [black](https://github.com/creativenull/efmls-configs-nvim/blob/ddc7c542aaad21da594edba233c15ae3fad01ea0/lua/efmls-configs/formatters/black.lua) one!?
> 
> ```lua
> local google_java = {
>     prefix = "google-java-format",
>     formatCommand = fs.executable("google-java-format")
>         .. " --aosp" -- Use AOSP style instead of Google Style (4-space indentation).
>         .. " $(echo -n ${--useless:rowStart} ${--useless:rowEnd}"
>         .. " | xargs -n4 -r sh -c 'echo"
>         .. " --skip-sorting-imports" -- Do not fix the import order.
>         .. " --skip-removing-unused-imports" -- Do not remove unused imports.
>         .. " --skip-reflowing-long-strings" -- Do not reflow string literals that exceed the column limit.
>         .. " --skip-javadoc-formatting" -- Do not reformat javadoc.
>         .. " --lines $(($1+1)):$(($3+1))'" -- Line range(s) to format, like 5:10 (1-based; default is all).
>         .. ") -",
>     formatCanRange = true,
>     formatStdin = true,
>     rootMarkers = {
>         ".project",
>         "classpath",
>         "pom.xml",
>     },
> }
> ```
> 
> I prefer 4 spaces 😄

I stole your code, I hope you wouldn't mind

**Comment by kimabrandt** [comment]
> > @kimabrandt it doesn't look cross-platform, so this won't work on Windows for example.
> 
> Until efm implements separation of range-formatting parameters, I think we can keep the old command in windows just like we did in black.

[`None-ls` uses a callback with the `range`-parameters](https://github.com/nvimtools/none-ls.nvim/blob/fbdcbf8e152529af846b3a333f039751829b84c2/lua/null-ls/builtins/formatting/google_java_format.lua#L17), to create a cross-platform `formatCommand`.

**Comment by creativenull** [comment]
> [`None-ls` uses a callback with the `range`-parameters](https://github.com/nvimtools/none-ls.nvim/blob/fbdcbf8e152529af846b3a333f039751829b84c2/lua/null-ls/builtins/formatting/google_java_format.lua#L17), to create a cross-platform `formatCommand`.

@kimabrandt I wish we could do something like this with efm, might have to make a request on [efm repo](https://github.com/mattn/efm-langserver) to use `rowStart`, `rowEnd`, etc. as standalone vars.

> Until efm implements separation of range-formatting parameters, I think we can keep the old command in windows just like we did in black.

@kuator yeah, this is fine with me too. You can go ahead and add the check for windows and only support range formatting for Linux/Mac. You can use this for reference: https://github.com/creativenull/efmls-configs-nvim/commit/7b79dfaaa40b32b3092c7b3cc872d37fc3412c66

**Comment by kuator** [comment]
> > [`None-ls` uses a callback with the `range`-parameters](https://github.com/nvimtools/none-ls.nvim/blob/fbdcbf8e152529af846b3a333f039751829b84c2/lua/null-ls/builtins/formatting/google_java_format.lua#L17), to create a cross-platform `formatCommand`.
> 
> @kimabrandt I wish we could do something like this with efm, might have to make a request on [efm repo](https://github.com/mattn/efm-langserver) to use `rowStart`, `rowEnd`, etc. as standalone vars.
> 
> > Until efm implements separation of range-formatting parameters, I think we can keep the old command in windows just like we did in black.
> 
> @kuator yeah, this is fine with me too. You can go ahead and add the check for windows and only support range formatting for Linux/Mac. You can use this for reference: [7b79dfa](https://github.com/creativenull/efmls-configs-nvim/commit/7b79dfaaa40b32b3092c7b3cc872d37fc3412c66)

Done

**Review by creativenull — APPROVED** [review]

**Pull request merged**
